spring.application.name=bot

#database.url=jdbc:mysql://localhost:3306/tinkoff_lab_db
#database.username=root
#database.password=sqlkilogodH19

translation.url=https://api.mymemory.translated.net/get?de=ektogod@mail.ru
openWeather.url=http://api.openweathermap.org
openWeather.key=01dede1cc7926f71f036644dd4350001

spring.datasource.url=jdbc:mysql://localhost:3306/my_db
spring.datasource.username=user
spring.datasource.password=1234
spring.jpa.hibernate.properties.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



ip.url=https://api.ipify.org?format=json
server.port=8080

#----------bot
bot.baseUrl=http://localhost:8080
email.url=http://localhost:8090/ektogod/email

