CREATE TABLE IF NOT EXISTS query (
ID INT NOT NULL AUTO_INCREMENT,
Username VARCHAR(100) NOT NULL,
IP VARCHAR(45) NOT NULL,
Original_Text VARCHAR(1000),
Original_Language VARCHAR(10),
Translated_Text VARCHAR(1000),
Target_Language VARCHAR(10),
Time DATETIME NOT NULL,
Status INT NOT NULL,
Message VARCHAR(1000),
PRIMARY KEY (ID)
)