package bot.states;

public enum States {
    TRANSLATE_LANGS, TRANSLATE_TEXT,
    SUBSCRIBE, DELETE_CITY,
    EMAIL_DELETE_CITY, EMAIL_GET, EMAIL_REGISTER, EMAIL_REGISTER_VALIDATION,  SUBSCRIBE_EMAIL, SUBSCRIBE_CITIES, EMAIL_UNSUBSCRIBE,
    NONE
}
