package bot.states;

public enum States {
    TRANSLATE_LANGS, TRANSLATE_TEXT,
    UNSUBSCRIBE, SUBSCRIBE, DELETE_CITY, GET_CITIES,
    EMAIL_DELETE_CITY, EMAIL_GET_CITIES, EMAIL_GET, EMAIL_REGISTER,  SUBSCRIBE_EMAIL, SUBSCRIBE_CITIES, EMAIL_UNSUBSCRIBE,
    NONE
}
