package bot.states;

public enum States {
    TRANSLATE_LANGS, TRANSLATE_TEXT,
    UNSUBSCRIBE, SUBSCRIBE, DELETE_CITY, GET_CITIES,
    EMAIL_DELETE_CITIES_EMAIL, EMAIL_DELETE_CITIES, EMAIL_GET_CITIES, EMAIL_REGISTER, EMAIL_SUBSCRIBE_CITIES_EMAIL, EMAIL_SUBSCRIBE_CITIES, EMAIL_UNSUBSCRIBE,
    NONE
}
